# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa430ca28c90929d446a60e32b58183229b72d4c01d04d0f4b500323d58fbdc6d31293892d4b772d13b1756602dc8f62e92e114dc6d41f9424549394ee7357c

test:
  secret_key_base: 48dd4df270f63dfb2b47c8604147b5d2646fe8678db8c0593623cafc96dfcb4685b661ef852d08145ed77806638947a56f36ce8f86e0f607df2a250e23b4ef4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
